export const theme = {
  colors: {
    primary: '#6115CD',
    background: '#F5F8FD',
    card: '#FFFFFF',
    textPrimary: '#111416',
    textSecondary: '#111416',
    textTertiary: '#68727D',
    border: '#E5E7EB',
    error: '#EF4444',
    white: '#FFFFFF',
    overlay: 'rgba(0, 0, 0, 0.4)',
    pillBackground: '#F3F4F6',
    avatarBackground: '#E5E7EB',
    transparent: 'transparent',
    likeRed: '#FF4B4B',
    skeleton: '#E5E7EB',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    xxxl: 32,
  },
  borderRadius: {
    sm: 4,
    sm2: 12,
    md: 16,
    lg: 100,
    xl: 20,
    full: 9999,
  },
  fonts: {
    regular: 'Manrope-Regular',
    medium: 'Manrope-Medium',
    semibold: 'Manrope-SemiBold',
    bold: 'Manrope-Bold',
  },
  fontSizes: {
    xs: 10,
    sm: 12,
    md: 14,
    lg: 15,
    xl: 16,
    xxl: 18,
    xxxl: 20,
  },
  fontWeights: {
    regular: '400' as const,
    medium: '500' as const,
    semibold: '600' as const,
    bold: '700' as const,
  },
  layout: {
    fullWidth: '100%' as const,
    fullHeight: '100%' as const,
    overflowHidden: 'hidden' as const,
    center: 'center' as const,
    row: 'row' as const,
    absolute: 'absolute' as const,
    paddingIOS: 44,
    headerHeight: 56,
  },
  lineHeights: {
    xs: 16,
    sm: 18,
    md: 20,
    lg: 21,
    xl: 24,
    xxl: 28,
  },
  dimensions: {
    zero: 0,
    flex1: 1,
    flex3: 3,
    avatarSm: 28,
    avatarMd: 32,
    avatarLg: 36,
    iconContainer: 48,
    filterBarHeight: 38,
    borderWidth: 1,
    interactionVerticalPadding: 6,
    microMargin: 2,
    aspectRatio1: 1,
    skeletonHeight: 16,
  },
  shadows: {
    light: {
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 10,
      elevation: 2,
    },
    micro: {
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    }
  }
};
